-- Migration: 013_footprint_module
-- Description: Add tables for user footprints (tool usage history) and AI personas

-- ============================================
-- 1. Create user_footprints table
-- ============================================
CREATE TABLE IF NOT EXISTS user_footprints (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    tool_name TEXT NOT NULL,
    input_context JSONB, -- The parameters/input provided by user
    output_result JSONB, -- The result generated by the tool
    is_deleted BOOLEAN DEFAULT false, -- Soft delete support
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for querying by user and time
CREATE INDEX IF NOT EXISTS idx_footprints_user_date 
    ON user_footprints(user_id, created_at DESC);

-- ============================================
-- 2. Create user_personas table
-- ============================================
CREATE TABLE IF NOT EXISTS user_personas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    persona_traits JSONB, -- Structured traits e.g. {"mbti": "INFJ", "keywords": ["creative", "analytical"]}
    analysis_text TEXT, -- Full narrative analysis
    suggestions TEXT, -- Actionable advice
    user_notes TEXT, -- User's manual overrides or notes
    is_latest BOOLEAN DEFAULT false, -- To mark the current active persona
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for quick lookup of latest persona
CREATE INDEX IF NOT EXISTS idx_personas_user_latest 
    ON user_personas(user_id) WHERE is_latest = true;

-- ============================================
-- 3. RLS Policies
-- ============================================

-- Footprints
ALTER TABLE user_footprints ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own footprints"
    ON user_footprints FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

CREATE POLICY "Users can insert own footprints"
    ON user_footprints FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own footprints"
    ON user_footprints FOR UPDATE
    TO authenticated
    USING (user_id = auth.uid());

-- Personas
ALTER TABLE user_personas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own personas"
    ON user_personas FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

CREATE POLICY "Users can insert own personas"
    ON user_personas FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own personas"
    ON user_personas FOR UPDATE
    TO authenticated
    USING (user_id = auth.uid());

-- ============================================
-- 4. Triggers
-- ============================================

-- Function to maintain single latest persona
CREATE OR REPLACE FUNCTION maintain_latest_persona()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_latest = true THEN
        UPDATE user_personas
        SET is_latest = false
        WHERE user_id = NEW.user_id AND id != NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_maintain_latest_persona
    BEFORE INSERT OR UPDATE ON user_personas
    FOR EACH ROW
    WHEN (NEW.is_latest = true)
    EXECUTE FUNCTION maintain_latest_persona();
